In [1]:
pip install yahoofinancials

Requirement already satisfied: yahoofinancials in c:\users\lee han ni\anaconda3\lib\site-packages (1.6)
Requirement already satisfied: pytz in c:\users\lee han ni\anaconda3\lib\site-packages (from yahoofinancials) (2021.3)
Requirement already satisfied: beautifulsoup4 in c:\users\lee han ni\anaconda3\lib\site-packages (from yahoofinancials) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\lee han ni\anaconda3\lib\site-packages (from beautifulsoup4->yahoofinancials) (2.2.1)
Note: you may need to restart the kernel to use updated packages.

## Import Libraries

In [2]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

## Import Data

In [3]:
from yahoofinancials import YahooFinancials

stocks= ['MSFT', 'SPY','GOOG','ADBE','NKE','TSLA',"FB","DELL","HPQ","AMZN"]

In [4]:
#original data before cleaning
yahoo_financials = YahooFinancials('WFC')
print(yahoo_financials.get_historical_price_data("2018-07-10", "2018-08-10", "monthly"))

{'WFC': {'eventsData': {'dividends': {'2018-08-01': {'amount': 0.43, 'date': 1533821400, 'formatted_date': '2018-08-09'}}}, 'firstTradeDate': {'formatted_date': '1972-06-01', 'date': 76253400}, 'currency': 'USD', 'instrumentType': 'EQUITY', 'timeZone': {'gmtOffset': -14400}, 'prices': [{'date': 1533096000, 'high': 59.529998779296875, 'low': 57.08000183105469, 'open': 57.959999084472656, 'close': 58.47999954223633, 'volume': 374293600, 'adjclose': 52.276119232177734, 'formatted_date': '2018-08-01'}]}}

## Data Extraction + Cleaning

In [5]:
df=[]

    
for item in stocks:
    yahoo_financials = YahooFinancials(item)
    data = yahoo_financials.get_historical_price_data("2020-02-01", "2022-02-01", "monthly")
    df.append(pd.DataFrame(data[item]['prices']))
    df[-1]['name'] = item
    
    for key in data[item]['prices']:
        #print(key)
        continue
## delete the first coloumn , clean data
dataframe=pd.concat(df)
dataframe=dataframe.drop(columns=['date'])
display(dataframe)

,high,low,open,close,volume,adjclose,formatted_date,name
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT
...,...,...,...,...,...,...,...,...
19,3549.989990,3273.989990,3496.399902,3285.040039,62527700,3285.040039,2021-09-01,AMZN
20,3479.000000,3176.250000,3289.010010,3372.429932,63673300,3372.429932,2021-10-01,AMZN
21,3762.149902,3283.550049,3361.800049,3507.070068,75799500,3507.070068,2021-11-01,AMZN
22,3559.879883,3303.899902,3545.000000,3334.340088,64381700,3334.340088,2021-12-01,AMZN
23,3428.000000,2707.040039,3351.000000,2991.469971,76232700,2991.469971,2022-01-01,AMZN

## Importing economic variables

In [13]:
#acquire retailsales data
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=RETAIL_SALES&apikey=4NABZ8IHZ6Q3TQ0H'
r = requests.get(url)
retailsales = r.json()


#appending retailsales data to dataframe
asd = [ ]
for x in range(0,25):
    asd.append(retailsales['data'][x]['value'])

print(asd[::-1])
newCol = pd.DataFrame(asd[::-1])
dataframe['RetailSales'] = newCol
dataframe.head(24)

['430527', '377210', '462286', '481205', '494905', '488949', '476247', '495722', '492362', '559932', '464362', '440019', '567933', '558181', '570641', '562929', '558031', '557018', '536229', '559399', '583223', '636842', '520915', '511946', '598911']

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp,FederalFunds,Change
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101,2.4,2.4,-8.419998
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2,2.2,-7.599991
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1,2.1,26.210007
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2,3.2,7.449997
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3,3,20.970001
5,216.380005,197.509995,203.139999,205.009995,770190800,201.868546,2020-07-01,MSFT,488949,8.4,72.5,3,3,1.869995
6,231.149994,203.139999,211.520004,225.529999,692423900,222.074097,2020-08-01,MSFT,476247,7.9,74.1,3.1,3.1,14.009995
7,232.860001,196.250000,225.509995,210.330002,768176300,207.607681,2020-09-01,MSFT,495722,6.9,80.4,2.6,2.6,-15.179993
8,225.210007,199.619995,213.490005,202.470001,631618000,199.849426,2020-10-01,MSFT,492362,6.7,81.8,2.6,2.6,-11.020004
9,228.119995,200.119995,204.289993,214.070007,573443000,211.299271,2020-11-01,MSFT,559932,6.7,76.9,2.8,2.8,9.780014
10,227.179993,209.110001,214.509995,222.419998,594761700,220.115967,2020-12-01,MSFT,464362,6.4,80.7,2.5,2.5,7.910004
11,242.639999,211.940002,222.529999,231.960007,648076400,229.557159,2021-01-01,MSFT,440019,6.2,79,3,3,9.430008
12,246.130005,227.880005,235.059998,232.380005,490962200,229.972809,2021-02-01,MSFT,567933,6.0,76.8,3.3,3.3,-2.679993
13,241.050003,224.259995,235.899994,235.770004,724945800,233.865067,2021-03-01,MSFT,558181,6.0,84.9,3.1,3.1,-0.129990
14,263.190002,238.050003,238.470001,252.179993,568661600,250.142487,2021-04-01,MSFT,570641,5.8,88.3,3.4,3.4,13.709991
15,254.350006,238.070007,253.399994,249.679993,495084900,247.662674,2021-05-01,MSFT,562929,5.9,82.9,4.6,4.6,-3.720001
16,271.649994,243.000000,251.229996,270.899994,508572200,269.331726,2021-06-01,MSFT,558031,5.4,85.5,4.2,4.2,19.669998
17,290.149994,269.600006,269.609985,284.910004,522672700,283.260620,2021-07-01,MSFT,557018,5.2,81.2,4.7,4.7,15.300018
18,305.839996,283.739990,286.359985,301.880005,441308900,300.132355,2021-08-01,MSFT,536229,4.7,70.3,4.6,4.6,15.520020
19,305.320007,281.619995,302.869995,281.920013,502918700,280.824524,2021-09-01,MSFT,559399,4.6,72.8,4.6,4.6,-20.949982
20,332.000000,280.250000,282.119995,331.619995,516515800,330.331360,2021-10-01,MSFT,583223,4.2,71.7,4.8,4.8,49.500000
21,349.670013,326.369995,331.359985,330.589996,509885200,329.305359,2021-11-01,MSFT,636842,3.9,67.4,4.9,4.9,-0.769989
22,344.299988,317.250000,335.130005,336.320007,625674800,335.626038,2021-12-01,MSFT,520915,4.0,70.6,4.8,4.8,1.190002
23,338.000000,276.049988,335.350006,310.980011,947531400,310.338318,2022-01-01,MSFT,511946,3.8,67.2,4.9,4.9,-24.369995

In [7]:
#acquire unemployment data
url = 'https://www.alphavantage.co/query?function=UNEMPLOYMENT&apikey=4NABZ8IHZ6Q3TQ0H'
r = requests.get(url)
unemployment = r.json()

#appending unemployment data to dataframe
asd = [ ]
for x in range(0,25):
    asd.append(unemployment['data'][x]['value'])

print(asd[::-1])
newCol = pd.DataFrame(asd[::-1])
dataframe['Unemployment'] = newCol
dataframe.head(25)

['4.4', '14.7', '13.2', '11.0', '10.2', '8.4', '7.9', '6.9', '6.7', '6.7', '6.4', '6.2', '6.0', '6.0', '5.8', '5.9', '5.4', '5.2', '4.7', '4.6', '4.2', '3.9', '4.0', '3.8', '3.6']

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2
5,216.380005,197.509995,203.139999,205.009995,770190800,201.868546,2020-07-01,MSFT,488949,8.4
6,231.149994,203.139999,211.520004,225.529999,692423900,222.074097,2020-08-01,MSFT,476247,7.9
7,232.860001,196.250000,225.509995,210.330002,768176300,207.607681,2020-09-01,MSFT,495722,6.9
8,225.210007,199.619995,213.490005,202.470001,631618000,199.849426,2020-10-01,MSFT,492362,6.7
9,228.119995,200.119995,204.289993,214.070007,573443000,211.299271,2020-11-01,MSFT,559932,6.7
10,227.179993,209.110001,214.509995,222.419998,594761700,220.115967,2020-12-01,MSFT,464362,6.4
11,242.639999,211.940002,222.529999,231.960007,648076400,229.557159,2021-01-01,MSFT,440019,6.2
12,246.130005,227.880005,235.059998,232.380005,490962200,229.972809,2021-02-01,MSFT,567933,6.0
13,241.050003,224.259995,235.899994,235.770004,724945800,233.865067,2021-03-01,MSFT,558181,6.0
14,263.190002,238.050003,238.470001,252.179993,568661600,250.142487,2021-04-01,MSFT,570641,5.8
15,254.350006,238.070007,253.399994,249.679993,495084900,247.662674,2021-05-01,MSFT,562929,5.9
16,271.649994,243.000000,251.229996,270.899994,508572200,269.331726,2021-06-01,MSFT,558031,5.4
17,290.149994,269.600006,269.609985,284.910004,522672700,283.260620,2021-07-01,MSFT,557018,5.2
18,305.839996,283.739990,286.359985,301.880005,441308900,300.132355,2021-08-01,MSFT,536229,4.7
19,305.320007,281.619995,302.869995,281.920013,502918700,280.824524,2021-09-01,MSFT,559399,4.6
20,332.000000,280.250000,282.119995,331.619995,516515800,330.331360,2021-10-01,MSFT,583223,4.2
21,349.670013,326.369995,331.359985,330.589996,509885200,329.305359,2021-11-01,MSFT,636842,3.9
22,344.299988,317.250000,335.130005,336.320007,625674800,335.626038,2021-12-01,MSFT,520915,4.0
23,338.000000,276.049988,335.350006,310.980011,947531400,310.338318,2022-01-01,MSFT,511946,3.8
0,339.079987,285.540009,323.350006,296.260010,2110214900,286.114319,2020-02-01,SPY,430527,4.4

In [8]:
#acquire consumer sentiment data
url = 'https://www.alphavantage.co/query?function=CONSUMER_SENTIMENT&apikey=4NABZ8IHZ6Q3TQ0H'
r = requests.get(url)
csentiment = r.json()

asd = [ ]
for x in range(0,25):
    asd.append(csentiment['data'][x]['value'])

print(asd[::-1])
newCol = pd.DataFrame(asd[::-1])
dataframe['CSentiment'] = newCol
dataframe.head(24)

['101', '89.1', '71.8', '72.3', '78.1', '72.5', '74.1', '80.4', '81.8', '76.9', '80.7', '79', '76.8', '84.9', '88.3', '82.9', '85.5', '81.2', '70.3', '72.8', '71.7', '67.4', '70.6', '67.2', '62.8']

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1
5,216.380005,197.509995,203.139999,205.009995,770190800,201.868546,2020-07-01,MSFT,488949,8.4,72.5
6,231.149994,203.139999,211.520004,225.529999,692423900,222.074097,2020-08-01,MSFT,476247,7.9,74.1
7,232.860001,196.250000,225.509995,210.330002,768176300,207.607681,2020-09-01,MSFT,495722,6.9,80.4
8,225.210007,199.619995,213.490005,202.470001,631618000,199.849426,2020-10-01,MSFT,492362,6.7,81.8
9,228.119995,200.119995,204.289993,214.070007,573443000,211.299271,2020-11-01,MSFT,559932,6.7,76.9
10,227.179993,209.110001,214.509995,222.419998,594761700,220.115967,2020-12-01,MSFT,464362,6.4,80.7
11,242.639999,211.940002,222.529999,231.960007,648076400,229.557159,2021-01-01,MSFT,440019,6.2,79
12,246.130005,227.880005,235.059998,232.380005,490962200,229.972809,2021-02-01,MSFT,567933,6.0,76.8
13,241.050003,224.259995,235.899994,235.770004,724945800,233.865067,2021-03-01,MSFT,558181,6.0,84.9
14,263.190002,238.050003,238.470001,252.179993,568661600,250.142487,2021-04-01,MSFT,570641,5.8,88.3
15,254.350006,238.070007,253.399994,249.679993,495084900,247.662674,2021-05-01,MSFT,562929,5.9,82.9
16,271.649994,243.000000,251.229996,270.899994,508572200,269.331726,2021-06-01,MSFT,558031,5.4,85.5
17,290.149994,269.600006,269.609985,284.910004,522672700,283.260620,2021-07-01,MSFT,557018,5.2,81.2
18,305.839996,283.739990,286.359985,301.880005,441308900,300.132355,2021-08-01,MSFT,536229,4.7,70.3
19,305.320007,281.619995,302.869995,281.920013,502918700,280.824524,2021-09-01,MSFT,559399,4.6,72.8
20,332.000000,280.250000,282.119995,331.619995,516515800,330.331360,2021-10-01,MSFT,583223,4.2,71.7
21,349.670013,326.369995,331.359985,330.589996,509885200,329.305359,2021-11-01,MSFT,636842,3.9,67.4
22,344.299988,317.250000,335.130005,336.320007,625674800,335.626038,2021-12-01,MSFT,520915,4.0,70.6
23,338.000000,276.049988,335.350006,310.980011,947531400,310.338318,2022-01-01,MSFT,511946,3.8,67.2

In [9]:
#acquire inflation expectation data
url = 'https://www.alphavantage.co/query?function=INFLATION_EXPECTATION&apikey=4NABZ8IHZ6Q3TQ0H'
r = requests.get(url)
inflationexp= r.json()

asd = [ ]
for x in range(0,25):
    asd.append(inflationexp['data'][x]['value'])

print(asd[::-1])
newCol = pd.DataFrame(asd[::-1]) #changed the order of formatted_date to match previous data
dataframe['InflationExp'] = newCol
dataframe.head(24)

['2.4', '2.2', '2.1', '3.2', '3', '3', '3.1', '2.6', '2.6', '2.8', '2.5', '3', '3.3', '3.1', '3.4', '4.6', '4.2', '4.7', '4.6', '4.6', '4.8', '4.9', '4.8', '4.9', '4.9']

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101,2.4
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3
5,216.380005,197.509995,203.139999,205.009995,770190800,201.868546,2020-07-01,MSFT,488949,8.4,72.5,3
6,231.149994,203.139999,211.520004,225.529999,692423900,222.074097,2020-08-01,MSFT,476247,7.9,74.1,3.1
7,232.860001,196.250000,225.509995,210.330002,768176300,207.607681,2020-09-01,MSFT,495722,6.9,80.4,2.6
8,225.210007,199.619995,213.490005,202.470001,631618000,199.849426,2020-10-01,MSFT,492362,6.7,81.8,2.6
9,228.119995,200.119995,204.289993,214.070007,573443000,211.299271,2020-11-01,MSFT,559932,6.7,76.9,2.8
10,227.179993,209.110001,214.509995,222.419998,594761700,220.115967,2020-12-01,MSFT,464362,6.4,80.7,2.5
11,242.639999,211.940002,222.529999,231.960007,648076400,229.557159,2021-01-01,MSFT,440019,6.2,79,3
12,246.130005,227.880005,235.059998,232.380005,490962200,229.972809,2021-02-01,MSFT,567933,6.0,76.8,3.3
13,241.050003,224.259995,235.899994,235.770004,724945800,233.865067,2021-03-01,MSFT,558181,6.0,84.9,3.1
14,263.190002,238.050003,238.470001,252.179993,568661600,250.142487,2021-04-01,MSFT,570641,5.8,88.3,3.4
15,254.350006,238.070007,253.399994,249.679993,495084900,247.662674,2021-05-01,MSFT,562929,5.9,82.9,4.6
16,271.649994,243.000000,251.229996,270.899994,508572200,269.331726,2021-06-01,MSFT,558031,5.4,85.5,4.2
17,290.149994,269.600006,269.609985,284.910004,522672700,283.260620,2021-07-01,MSFT,557018,5.2,81.2,4.7
18,305.839996,283.739990,286.359985,301.880005,441308900,300.132355,2021-08-01,MSFT,536229,4.7,70.3,4.6
19,305.320007,281.619995,302.869995,281.920013,502918700,280.824524,2021-09-01,MSFT,559399,4.6,72.8,4.6
20,332.000000,280.250000,282.119995,331.619995,516515800,330.331360,2021-10-01,MSFT,583223,4.2,71.7,4.8
21,349.670013,326.369995,331.359985,330.589996,509885200,329.305359,2021-11-01,MSFT,636842,3.9,67.4,4.9
22,344.299988,317.250000,335.130005,336.320007,625674800,335.626038,2021-12-01,MSFT,520915,4.0,70.6,4.8
23,338.000000,276.049988,335.350006,310.980011,947531400,310.338318,2022-01-01,MSFT,511946,3.8,67.2,4.9

In [10]:
#acquire federal funds data
URL='https://www.alphavantage.co/query?function=FEDERAL_FUNDS_RATE&interval=monthly&apikey=4NABZ8IHZ6Q3TQ0H'

r = requests.get(url)
federalfunds= r.json()

asd = [ ]
for x in range(0,25):
    asd.append(federalfunds['data'][x]['value'])

print(asd[::-1])
newCol = pd.DataFrame(asd[::-1]) #changed the order to match previous data
dataframe['FederalFunds'] = newCol
dataframe.head(24)

['2.4', '2.2', '2.1', '3.2', '3', '3', '3.1', '2.6', '2.6', '2.8', '2.5', '3', '3.3', '3.1', '3.4', '4.6', '4.2', '4.7', '4.6', '4.6', '4.8', '4.9', '4.8', '4.9', '4.9']

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp,FederalFunds
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101,2.4,2.4
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2,2.2
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1,2.1
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2,3.2
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3,3
5,216.380005,197.509995,203.139999,205.009995,770190800,201.868546,2020-07-01,MSFT,488949,8.4,72.5,3,3
6,231.149994,203.139999,211.520004,225.529999,692423900,222.074097,2020-08-01,MSFT,476247,7.9,74.1,3.1,3.1
7,232.860001,196.250000,225.509995,210.330002,768176300,207.607681,2020-09-01,MSFT,495722,6.9,80.4,2.6,2.6
8,225.210007,199.619995,213.490005,202.470001,631618000,199.849426,2020-10-01,MSFT,492362,6.7,81.8,2.6,2.6
9,228.119995,200.119995,204.289993,214.070007,573443000,211.299271,2020-11-01,MSFT,559932,6.7,76.9,2.8,2.8
10,227.179993,209.110001,214.509995,222.419998,594761700,220.115967,2020-12-01,MSFT,464362,6.4,80.7,2.5,2.5
11,242.639999,211.940002,222.529999,231.960007,648076400,229.557159,2021-01-01,MSFT,440019,6.2,79,3,3
12,246.130005,227.880005,235.059998,232.380005,490962200,229.972809,2021-02-01,MSFT,567933,6.0,76.8,3.3,3.3
13,241.050003,224.259995,235.899994,235.770004,724945800,233.865067,2021-03-01,MSFT,558181,6.0,84.9,3.1,3.1
14,263.190002,238.050003,238.470001,252.179993,568661600,250.142487,2021-04-01,MSFT,570641,5.8,88.3,3.4,3.4
15,254.350006,238.070007,253.399994,249.679993,495084900,247.662674,2021-05-01,MSFT,562929,5.9,82.9,4.6,4.6
16,271.649994,243.000000,251.229996,270.899994,508572200,269.331726,2021-06-01,MSFT,558031,5.4,85.5,4.2,4.2
17,290.149994,269.600006,269.609985,284.910004,522672700,283.260620,2021-07-01,MSFT,557018,5.2,81.2,4.7,4.7
18,305.839996,283.739990,286.359985,301.880005,441308900,300.132355,2021-08-01,MSFT,536229,4.7,70.3,4.6,4.6
19,305.320007,281.619995,302.869995,281.920013,502918700,280.824524,2021-09-01,MSFT,559399,4.6,72.8,4.6,4.6
20,332.000000,280.250000,282.119995,331.619995,516515800,330.331360,2021-10-01,MSFT,583223,4.2,71.7,4.8,4.8
21,349.670013,326.369995,331.359985,330.589996,509885200,329.305359,2021-11-01,MSFT,636842,3.9,67.4,4.9,4.9
22,344.299988,317.250000,335.130005,336.320007,625674800,335.626038,2021-12-01,MSFT,520915,4.0,70.6,4.8,4.8
23,338.000000,276.049988,335.350006,310.980011,947531400,310.338318,2022-01-01,MSFT,511946,3.8,67.2,4.9,4.9

## Creating new columns

In [11]:
#creating new column 'change'
dataframe['Change'] = dataframe['close'] - dataframe['open']
               
dataframe

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp,FederalFunds,Change
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101,2.4,2.4,-8.419998
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2,2.2,-7.599991
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1,2.1,26.210007
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2,3.2,7.449997
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3,3,20.970001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,3549.989990,3273.989990,3496.399902,3285.040039,62527700,3285.040039,2021-09-01,AMZN,559399,4.6,72.8,4.6,4.6,-211.359863
20,3479.000000,3176.250000,3289.010010,3372.429932,63673300,3372.429932,2021-10-01,AMZN,583223,4.2,71.7,4.8,4.8,83.419922
21,3762.149902,3283.550049,3361.800049,3507.070068,75799500,3507.070068,2021-11-01,AMZN,636842,3.9,67.4,4.9,4.9,145.270020
22,3559.879883,3303.899902,3545.000000,3334.340088,64381700,3334.340088,2021-12-01,AMZN,520915,4.0,70.6,4.8,4.8,-210.659912
23,3428.000000,2707.040039,3351.000000,2991.469971,76232700,2991.469971,2022-01-01,AMZN,511946,3.8,67.2,4.9,4.9,-359.530029

In [14]:
#creating new column 'change_class'
def fun(num):
    if num <0:
        return "down"
    if num>0:
        return "up"
    if num==0:
        return "same"
    
dataframe['change_class'] = dataframe['Change'].apply(fun)
dataframe

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp,FederalFunds,Change,change_class
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101,2.4,2.4,-8.419998,down
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2,2.2,-7.599991,down
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1,2.1,26.210007,up
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2,3.2,7.449997,up
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3,3,20.970001,up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,3549.989990,3273.989990,3496.399902,3285.040039,62527700,3285.040039,2021-09-01,AMZN,559399,4.6,72.8,4.6,4.6,-211.359863,down
20,3479.000000,3176.250000,3289.010010,3372.429932,63673300,3372.429932,2021-10-01,AMZN,583223,4.2,71.7,4.8,4.8,83.419922,up
21,3762.149902,3283.550049,3361.800049,3507.070068,75799500,3507.070068,2021-11-01,AMZN,636842,3.9,67.4,4.9,4.9,145.270020,up
22,3559.879883,3303.899902,3545.000000,3334.340088,64381700,3334.340088,2021-12-01,AMZN,520915,4.0,70.6,4.8,4.8,-210.659912,down
23,3428.000000,2707.040039,3351.000000,2991.469971,76232700,2991.469971,2022-01-01,AMZN,511946,3.8,67.2,4.9,4.9,-359.530029,down

## Changing variable type

In [15]:
dataframe['RetailSales']=dataframe['RetailSales'].astype(int)  # changed from string to respective
dataframe['Unemployment']=dataframe['Unemployment'].astype(float)
dataframe['CSentiment']=dataframe['CSentiment'].astype(float)
dataframe['InflationExp']=dataframe['InflationExp'].astype(float)
dataframe['FederalFunds']=dataframe['FederalFunds'].astype(float)
dataframe.reset_index(drop=True)

,high,low,open,close,volume,adjclose,formatted_date,name,RetailSales,Unemployment,CSentiment,InflationExp,FederalFunds,Change,change_class
0,190.699997,152.000000,170.429993,162.009995,887522300,158.651062,2020-02-01,MSFT,430527,4.4,101.0,2.4,2.4,-8.419998,down
1,175.000000,132.520004,165.309998,157.710007,1612695500,154.862061,2020-03-01,MSFT,377210,14.7,89.1,2.2,2.2,-7.599991,down
2,180.399994,150.360001,153.000000,179.210007,984705000,175.973785,2020-04-01,MSFT,462286,13.2,71.8,2.1,2.1,26.210007,up
3,187.509995,173.800003,175.800003,183.250000,688845000,179.940857,2020-05-01,MSFT,481205,11.0,72.3,3.2,3.2,7.449997,up
4,204.399994,181.350006,182.539993,203.509995,764965400,200.391525,2020-06-01,MSFT,494905,10.2,78.1,3.0,3.0,20.970001,up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,3549.989990,3273.989990,3496.399902,3285.040039,62527700,3285.040039,2021-09-01,AMZN,559399,4.6,72.8,4.6,4.6,-211.359863,down
236,3479.000000,3176.250000,3289.010010,3372.429932,63673300,3372.429932,2021-10-01,AMZN,583223,4.2,71.7,4.8,4.8,83.419922,up
237,3762.149902,3283.550049,3361.800049,3507.070068,75799500,3507.070068,2021-11-01,AMZN,636842,3.9,67.4,4.9,4.9,145.270020,up
238,3559.879883,3303.899902,3545.000000,3334.340088,64381700,3334.340088,2021-12-01,AMZN,520915,4.0,70.6,4.8,4.8,-210.659912,down
239,3428.000000,2707.040039,3351.000000,2991.469971,76232700,2991.469971,2022-01-01,AMZN,511946,3.8,67.2,4.9,4.9,-359.530029,down